name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGM0ZmUyODctNTg3Yi00NzUxLTg4NzgtM2JkYWM5NDYyNWJhIiwidGVuYW50X2lkIjoiZDI4ZDE0N2ZmMDA1NWI5NmM5NjVhNjkwYjRjMTMxNWNhNmI0MWE2MDUyODQ5MmNmYTY3OTQwOGM3YmRlYTIzYiIsImludGVybmFsX3NlY3JldCI6ImE0MzE5Zjc5LTUwY2ItNDQ4MC04ZmE3LWNlNzgwNGQ5NzUwNSJ9.7ipEdRKcT3tDu-S1fq2mFapxKBZKMNH0nSe35o4_UaQ"
JWT_SECRET="knkkjiojknkn897hh8y"

#DATABASE_URL="${secrets.DATABASE_URL}"
#JWT_SECRET="${secrets.JWT_SECRET}"